# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Fortify Engineering
email: 
description: > # this means to ignore newlines until "baseurl:"
  Fortify Engineering Github repositories
future: true
#baseurl: "" # the subpath of your site, e.g. /blog
#url: "http://localhost:4000" # the base hostname & protocol for your site, e.g. http://example.com

baseurl: "/fortify/website.github.houston.softwaregrp.net" # the subpath of your site, e.g. /blog
url: "https://pages.github.houston.softwaregrp.net" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
  - css/Semantic-UI-CSS/readme.md

#host: https://pages.github.hpe.com/eran-argaman

### content configuration ###
title:       "Fortify Engineering Github Repositiries"
keywords:    "HPE, Fortify, security"
description: "Fortify Engineering Github Repositiries"
source_link: ""
highlighter: rouge

kramdown:
  auto_ids:  false
  

